Import libraries

In [2]:
import yfinance as yf
import pandas as pd
import os

In [3]:
# Define which tickers we want and the date range
tickers = ["SPY", "QQQ", "AAPL"]
start_date = "2014-01-01"
end_date = "2024-01-01"

# Download the data
data = yf.download(tickers, start=start_date, end=end_date)

# Preview the first 5 rows
data.head()

[*********************100%***********************]  3 of 3 completed

Price           Close                              High             \
Ticker           AAPL        QQQ         SPY       AAPL        QQQ
Date
2014-01-02  17.124887  78.956848  148.198456  17.245632  79.237323
2014-01-03  16.748722  78.386871  148.174133  17.142532  79.029238
2014-01-06  16.840048  78.097366  147.744797  16.928902  78.495455
2014-01-07  16.719618  78.821152  148.652176  16.902900  78.938766
2014-01-08  16.825510  78.993050  148.684570  16.890525  79.210193

Price                         Low                              Open  \
Ticker             SPY       AAPL        QQQ         SPY       AAPL
Date
2014-01-02  149.130172  17.090522  78.730663  147.841974  17.203836
2014-01-03  148.749368  16.731693  78.368780  147.963491  17.116527
2014-01-06  148.717013  16.520231  77.807849  147.517947  16.639428
2014-01-07  148.903330  16.653983  78.314491  148.222780  16.852126
2014-01-08  148.935725  16.677831  78.667342  148.174152  16.681545

Price                                 Volume
Ticker            QQQ         SPY       AAPL       QQQ        SPY
Date
2014-01-02  79.210182  149.057247  234684800  29177500  119636900
2014-01-03  78.956856  148.449592  392467600  35723700   81390600
2014-01-06  78.404982  148.660306  412610800  32073100  108028200
2014-01-07  78.459253  148.336205  317209200  25860600   86144200
2014-01-08  78.839245  148.627852  258529600  27197400   96582300

In [4]:
# Pull out just SPY's data
spy = data["Close"]["SPY"]

# Preview it
spy.head()

Date
2014-01-02    148.198456
2014-01-03    148.174133
2014-01-06    147.744797
2014-01-07    148.652176
2014-01-08    148.684570
Name: SPY, dtype: float64

In [5]:
# Get all OHLCV columns for SPY
spy = data.xs("SPY", axis=1, level=1)

# Preview it
spy.head()

Price            Close        High         Low        Open     Volume
Date
2014-01-02  148.198456  149.130172  147.841974  149.057247  119636900
2014-01-03  148.174133  148.749368  147.963491  148.449592   81390600
2014-01-06  147.744797  148.717013  147.517947  148.660306  108028200
2014-01-07  148.652176  148.903330  148.222780  148.336205   86144200
2014-01-08  148.684570  148.935725  148.174152  148.627852   96582300

In [6]:
# Create the raw data folder if it doesn't exist
os.makedirs("../data/raw", exist_ok=True)

# Save SPY data as a CSV
spy.to_csv("../data/raw/SPY.csv")

print("Saved!")

Saved!

In [7]:
# Load SPY data from CSV instead of downloading
spy_loaded = pd.read_csv("../data/raw/SPY.csv", index_col="Date", parse_dates=True)

spy_loaded.head()

                 Close        High         Low        Open     Volume
Date
2014-01-02  148.198456  149.130172  147.841974  149.057247  119636900
2014-01-03  148.174133  148.749368  147.963491  148.449592   81390600
2014-01-06  147.744797  148.717013  147.517947  148.660306  108028200
2014-01-07  148.652176  148.903330  148.222780  148.336205   86144200
2014-01-08  148.684570  148.935725  148.174152  148.627852   96582300

In [8]:
# Save all tickers to CSV
tickers = ["SPY", "QQQ", "AAPL"]

for ticker in tickers:
    ticker_data = data.xs(ticker, axis=1, level=1)
    ticker_data.to_csv(f"../data/raw/{ticker}.csv")
    print(f"Saved {ticker}")

Saved SPY
Saved QQQ
Saved AAPL